# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels: [ ]
    ignore:
      - biz.aQute.bnd:biz.aQute.tester.junit-platform
      - ch.qos.logback.contrib:logback-jackson
      - ch.qos.logback.contrib:logback-json-classic
      - ch.qos.logback.contrib:logback-json-core
      - ch.qos.logback:logback-classic
      - ch.qos.logback:logback-core
      - ch.qos.reload4j:reload4j
      - com.fasterxml.jackson.core:jackson-annotations
      - com.fasterxml.jackson.core:jackson-core
      - com.fasterxml.jackson.core:jackson-databind
      - com.fasterxml.jackson.dataformat:jackson-dataformat-cbor
      - com.fasterxml.jackson.dataformat:jackson-dataformat-xml
      - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
      - com.fasterxml.jackson.datatype:jackson-datatype-jsr310
      - com.fasterxml.jackson.jaxrs:jackson-jaxrs-base
      - com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider
      - com.fasterxml.jackson.module:jackson-module-jaxb-annotations
      - com.fasterxml.woodstox:woodstox-core
      - com.github.ben-manes.caffeine:caffeine
      - com.google.code.findbugs:jsr305
      - com.google.code.gson:gson
      - com.google.dagger:dagger
      - com.google.errorprone:error_prone_annotations
      - com.google.guava:failureaccess
      - com.google.guava:guava
      - com.google.guava:listenablefuture
      - com.google.inject:guice
      - com.google.j2objc:j2objc-annotations
      - com.googlecode.efficient-java-matrix-library:core
      - com.googlecode.efficient-java-matrix-library:equation
      - com.hivemq:hivemq-mqtt-client
      - com.igormaznitsa:jbbp
      - com.jayway.jsonpath:json-path
      - com.madgag:animated-gif-lib
      - com.neuronrobotics:nrjavaserial
      - com.sun.activation:jakarta.activation
      - com.sun.istack:istack-commons-runtime
      - com.sun.xml.bind:jaxb-osgi
      - com.thoughtworks.xstream:xstream
      - de.erichseifert.vectorgraphics2d:VectorGraphics2D
      - de.focus-shift:jollyday-core
      - de.focus-shift:jollyday-jackson
      - de.rototor.pdfbox:graphics2d
      - io.dropwizard.metrics:metrics-core
      - io.github.classgraph:classgraph
      - io.github.x-stream:mxparser
      - io.micrometer:micrometer-commons
      - io.micrometer:micrometer-core
      - io.micrometer:micrometer-observation
      - io.netty:netty-buffer
      - io.netty:netty-codec
      - io.netty:netty-common
      - io.netty:netty-handler
      - io.netty:netty-resolver
      - io.netty:netty-transport
      - io.netty:netty-transport-native-unix-common
      - io.reactivex.rxjava2:rxjava
      - io.swagger.core.v3:swagger-annotations
      - io.swagger.core.v3:swagger-core
      - io.swagger.core.v3:swagger-integration
      - io.swagger.core.v3:swagger-jaxrs2
      - io.swagger.core.v3:swagger-models
      - jakarta.activation:jakarta.activation-api
      - jakarta.annotation:jakarta.annotation-api
      - jakarta.inject:jakarta.inject-api
      - jakarta.validation:jakarta.validation-api
      - jakarta.ws.rs:jakarta.ws.rs-api
      - jakarta.xml.bind:jakarta.xml.bind-api
      - javax.activation:activation
      - javax.annotation:javax.annotation-api
      - javax.inject:javax.inject
      - javax.measure:unit-api
      - javax.servlet:javax.servlet-api
      - javax.websocket:javax.websocket-api
      - javax.websocket:javax.websocket-client-api
      - javax.xml.bind:jaxb-api
      - javax.xml.soap:javax.xml.soap-api
      - javax.xml.stream:stax-api
      - net.bytebuddy:byte-buddy
      - net.bytebuddy:byte-buddy-agent
      - net.java.dev.jna:jna
      - net.java.dev.jna:jna-platform
      - net.minidev:accessors-smart
      - net.minidev:json-smart
      - net.wimpi:jamod
      - org.antlr:antlr-runtime
      - org.apache.aries.component-dsl:org.apache.aries.component-dsl.component-dsl
      - org.apache.aries.jax.rs:org.apache.aries.jax.rs.whiteboard
      - org.apache.aries.jpa.javax.persistence:javax.persistence_2.1
      - org.apache.aries.jpa:org.apache.aries.jpa.container
      - org.apache.aries.spec:org.apache.aries.javax.jax.rs-api
      - org.apache.aries.spifly:org.apache.aries.spifly.dynamic.bundle
      - org.apache.aries.tx-control:tx-control-provider-jdbc-xa
      - org.apache.aries.tx-control:tx-control-provider-jpa-xa
      - org.apache.aries.tx-control:tx-control-service-xa
      - org.apache.commons:commons-collections4
      - org.apache.commons:commons-lang3
      - org.apache.commons:commons-pool2
      - org.apache.cxf:cxf-core
      - org.apache.cxf:cxf-rt-frontend-jaxrs
      - org.apache.cxf:cxf-rt-rs-client
      - org.apache.cxf:cxf-rt-rs-sse
      - org.apache.cxf:cxf-rt-security
      - org.apache.cxf:cxf-rt-transports-http
      - org.apache.directory.api:api-asn1-api
      - org.apache.directory.api:api-asn1-ber
      - org.apache.directory.api:api-i18n
      - org.apache.directory.api:api-ldap-model
      - org.apache.directory.api:api-util
      - org.apache.felix:org.apache.felix.cm.json
      - org.apache.felix:org.apache.felix.configadmin
      - org.apache.felix:org.apache.felix.configadmin.plugin.interpolation
      - org.apache.felix:org.apache.felix.configurator
      - org.apache.felix:org.apache.felix.fileinstall
      - org.apache.felix:org.apache.felix.framework
      - org.apache.felix:org.apache.felix.gogo.command
      - org.apache.felix:org.apache.felix.gogo.runtime
      - org.apache.felix:org.apache.felix.gogo.shell
      - org.apache.felix:org.apache.felix.http.servlet-api
      - org.apache.felix:org.apache.felix.inventory
      - org.apache.felix:org.apache.felix.scr
      - org.apache.felix:org.apache.felix.utils
      - org.apache.felix:org.apache.felix.webconsole
      - org.apache.felix:org.apache.felix.webconsole.plugins.ds
      - org.apache.geronimo.specs:geronimo-activation_1.1_spec
      - org.apache.geronimo.specs:geronimo-jaxws_2.2_spec
      - org.apache.geronimo.specs:geronimo-json_1.1_spec
      - org.apache.geronimo.specs:geronimo-osgi-locator
      - org.apache.geronimo.specs:geronimo-saaj_1.3_spec
      - org.apache.geronimo.specs:geronimo-stax-api_1.2_spec
      - org.apache.karaf.config:org.apache.karaf.config.core
      - org.apache.karaf.diagnostic:org.apache.karaf.diagnostic.boot
      - org.apache.karaf.features:base
      - org.apache.karaf.features:framework:kar:4.4.7:provided
      - org.apache.karaf.features:org.apache.karaf.features.core
      - org.apache.karaf.features:org.apache.karaf.features.extension
      - org.apache.karaf.features:standard:xml:features:4.4.7:provided
      - org.apache.karaf.jaas:org.apache.karaf.jaas.boot
      - org.apache.karaf.jaas:org.apache.karaf.jaas.config
      - org.apache.karaf.jaas:org.apache.karaf.jaas.modules
      - org.apache.karaf.kar:org.apache.karaf.kar.core
      - org.apache.karaf.log:org.apache.karaf.log.core
      - org.apache.karaf.shell:org.apache.karaf.shell.core
      - org.apache.karaf.specs:org.apache.karaf.specs.activator
      - org.apache.karaf.specs:org.apache.karaf.specs.java.xml
      - org.apache.karaf.specs:org.apache.karaf.specs.java.xml.ws
      - org.apache.karaf.specs:org.apache.karaf.specs.locator
      - org.apache.karaf.wrapper:org.apache.karaf.wrapper.core
      - org.apache.karaf:org.apache.karaf.client
      - org.apache.karaf:org.apache.karaf.main
      - org.apache.karaf:org.apache.karaf.util
      - org.apache.logging.log4j:log4j-api
      - org.apache.logging.log4j:log4j-core
      - org.apache.maven.plugin-tools:maven-plugin-annotations
      - org.apache.maven.resolver:maven-resolver-api
      - org.apache.maven.resolver:maven-resolver-impl
      - org.apache.maven.resolver:maven-resolver-named-locks
      - org.apache.maven.resolver:maven-resolver-spi
      - org.apache.maven.resolver:maven-resolver-util
      - org.apache.maven:maven-artifact
      - org.apache.maven:maven-model
      - org.apache.maven:maven-plugin-api
      - org.apache.mina:mina-core
      - org.apache.pdfbox:fontbox
      - org.apache.pdfbox:pdfbox
      - org.apache.pdfbox:pdfbox-io
      - org.apache.servicemix.bundles:org.apache.servicemix.bundles.antlr
      - org.apache.servicemix.bundles:org.apache.servicemix.bundles.saaj-impl
      - org.apache.servicemix.specs:org.apache.servicemix.specs.activation-api-1.2.1
      - org.apache.servicemix.specs:org.apache.servicemix.specs.annotation-api-1.3
      - org.apache.servicemix.specs:org.apache.servicemix.specs.jaxb-api-2.3
      - org.apache.servicemix.specs:org.apache.servicemix.specs.jaxws-api-2.3
      - org.apache.servicemix.specs:org.apache.servicemix.specs.locator
      - org.apache.servicemix.specs:org.apache.servicemix.specs.saaj-api-1.3
      - org.apache.servicemix.specs:org.apache.servicemix.specs.saaj-api-1.4
      - org.apache.servicemix.specs:org.apache.servicemix.specs.stax-api-1.0
      - org.apache.servicemix.specs:org.apache.servicemix.specs.stax-api-1.2
      - org.apache.sling:org.apache.sling.commons.johnzon
      - org.apache.sshd:sshd-osgi
      - org.apache.tomcat:tomcat-servlet-api
      - org.apache.ws.xmlschema:xmlschema-core
      - org.apache.xbean:xbean-asm-util
      - org.apache.xbean:xbean-bundleutils
      - org.apache.xbean:xbean-finder
      - org.apiguardian:apiguardian-api
      - org.bitbucket.b_c:jose4j
      - org.bouncycastle:bcpkix-jdk18on
      - org.bouncycastle:bcprov-jdk18on
      - org.bouncycastle:bcutil-jdk18on
      - org.checkerframework:checker-qual
      - org.codehaus.mojo:animal-sniffer-annotations
      - org.codehaus.plexus:plexus-classworlds
      - org.codehaus.plexus:plexus-component-annotations
      - org.codehaus.plexus:plexus-utils
      - org.codehaus.woodstox:stax2-api
      - org.eclipse.californium:californium-core
      - org.eclipse.californium:californium-legal
      - org.eclipse.californium:californium-osgi
      - org.eclipse.californium:element-connector
      - org.eclipse.californium:scandium
      - org.eclipse.emf:org.eclipse.emf.codegen
      - org.eclipse.emf:org.eclipse.emf.codegen.ecore
      - org.eclipse.emf:org.eclipse.emf.common
      - org.eclipse.emf:org.eclipse.emf.ecore
      - org.eclipse.emf:org.eclipse.emf.ecore.change
      - org.eclipse.emf:org.eclipse.emf.ecore.xmi
      - org.eclipse.emf:org.eclipse.emf.mwe.core
      - org.eclipse.emf:org.eclipse.emf.mwe.utils
      - org.eclipse.emf:org.eclipse.emf.mwe2.language
      - org.eclipse.emf:org.eclipse.emf.mwe2.launch
      - org.eclipse.emf:org.eclipse.emf.mwe2.lib
      - org.eclipse.emf:org.eclipse.emf.mwe2.runtime
      - org.eclipse.jdt:ecj
      - org.eclipse.jdt:org.eclipse.jdt.annotation
      - org.eclipse.jdt:org.eclipse.jdt.core
      - org.eclipse.jdt:org.eclipse.jdt.debug
      - org.eclipse.jdt:org.eclipse.jdt.launching
      - org.eclipse.jetty.http2:http2-client
      - org.eclipse.jetty.http2:http2-common
      - org.eclipse.jetty.http2:http2-hpack
      - org.eclipse.jetty.http2:http2-server
      - org.eclipse.jetty.orbit:javax.security.auth.message
      - org.eclipse.jetty.websocket:javax-websocket-client-impl
      - org.eclipse.jetty.websocket:javax-websocket-server-impl
      - org.eclipse.jetty.websocket:websocket-api
      - org.eclipse.jetty.websocket:websocket-client
      - org.eclipse.jetty.websocket:websocket-common
      - org.eclipse.jetty.websocket:websocket-server
      - org.eclipse.jetty.websocket:websocket-servlet
      - org.eclipse.jetty:jetty-alpn-client
      - org.eclipse.jetty:jetty-alpn-java-client
      - org.eclipse.jetty:jetty-annotations
      - org.eclipse.jetty:jetty-client
      - org.eclipse.jetty:jetty-continuation
      - org.eclipse.jetty:jetty-deploy
      - org.eclipse.jetty:jetty-http
      - org.eclipse.jetty:jetty-io
      - org.eclipse.jetty:jetty-jaas
      - org.eclipse.jetty:jetty-jaspi
      - org.eclipse.jetty:jetty-jmx
      - org.eclipse.jetty:jetty-jndi
      - org.eclipse.jetty:jetty-plus
      - org.eclipse.jetty:jetty-proxy
      - org.eclipse.jetty:jetty-rewrite
      - org.eclipse.jetty:jetty-security
      - org.eclipse.jetty:jetty-server
      - org.eclipse.jetty:jetty-servlet
      - org.eclipse.jetty:jetty-servlets
      - org.eclipse.jetty:jetty-util
      - org.eclipse.jetty:jetty-util-ajax
      - org.eclipse.jetty:jetty-webapp
      - org.eclipse.jetty:jetty-xml
      - org.eclipse.lsp4j:org.eclipse.lsp4j
      - org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc
      - org.eclipse.orbit.bundles:com.google.inject
      - org.eclipse.orbit.bundles:org.antlr.runtime
      - org.eclipse.platform:org.eclipse.core.commands
      - org.eclipse.platform:org.eclipse.core.contenttype
      - org.eclipse.platform:org.eclipse.core.expressions
      - org.eclipse.platform:org.eclipse.core.filesystem
      - org.eclipse.platform:org.eclipse.core.jobs
      - org.eclipse.platform:org.eclipse.core.resources
      - org.eclipse.platform:org.eclipse.core.runtime
      - org.eclipse.platform:org.eclipse.core.variables
      - org.eclipse.platform:org.eclipse.debug.core
      - org.eclipse.platform:org.eclipse.equinox.app
      - org.eclipse.platform:org.eclipse.equinox.common
      - org.eclipse.platform:org.eclipse.equinox.event
      - org.eclipse.platform:org.eclipse.equinox.log.stream
      - org.eclipse.platform:org.eclipse.equinox.metatype
      - org.eclipse.platform:org.eclipse.equinox.preferences
      - org.eclipse.platform:org.eclipse.equinox.registry
      - org.eclipse.platform:org.eclipse.osgi
      - org.eclipse.platform:org.eclipse.text
      - org.eclipse.sisu:org.eclipse.sisu.inject
      - org.eclipse.sisu:org.eclipse.sisu.plexus
      - org.eclipse.xtend:org.eclipse.xtend.lib
      - org.eclipse.xtend:org.eclipse.xtend.lib.macro
      - org.eclipse.xtext:org.eclipse.xtext
      - org.eclipse.xtext:org.eclipse.xtext.common.types
      - org.eclipse.xtext:org.eclipse.xtext.ecore
      - org.eclipse.xtext:org.eclipse.xtext.ide
      - org.eclipse.xtext:org.eclipse.xtext.util
      - org.eclipse.xtext:org.eclipse.xtext.xbase
      - org.eclipse.xtext:org.eclipse.xtext.xbase.ide
      - org.eclipse.xtext:org.eclipse.xtext.xbase.lib
      - org.eclipse.xtext:org.eclipse.xtext.xtext.generator
      - org.glassfish.hk2.external:aopalliance-repackaged
      - org.glassfish.hk2:hk2-api
      - org.glassfish.hk2:hk2-locator
      - org.glassfish.hk2:hk2-utils
      - org.glassfish.hk2:osgi-resource-locator
      - org.glassfish.jaxb:jaxb-runtime
      - org.glassfish.jaxb:txw2
      - org.hamcrest:hamcrest
      - org.hdrhistogram:HdrHistogram
      - org.javassist:javassist
      - org.jctools:jctools-core
      - org.jetbrains:annotations
      - org.jline:jline
      - org.jmdns:jmdns
      - org.junit.jupiter:junit-jupiter-api
      - org.junit.jupiter:junit-jupiter-engine
      - org.junit.jupiter:junit-jupiter-params
      - org.junit.platform:junit-platform-commons
      - org.junit.platform:junit-platform-engine
      - org.junit.platform:junit-platform-launcher
      - org.jupnp:org.jupnp
      - org.jvnet.staxex:stax-ex
      - org.knowm.xchart:xchart
      - org.latencyutils:LatencyUtils
      - org.mockito:mockito-core
      - org.mockito:mockito-junit-jupiter
      - org.objenesis:objenesis
      - org.openhab.osgiify:com.google.dagger
      - org.openhab.osgiify:io.methvin.directory-watcher
      - org.openhab.osgiify:si.uom.si-units
      - org.opentest4j:opentest4j
      - org.ops4j.base:ops4j-base-lang
      - org.ops4j.base:ops4j-base-util-collections
      - org.ops4j.base:ops4j-base-util-property
      - org.ops4j.base:ops4j-base-util-xml
      - org.ops4j.pax.logging:pax-logging-api
      - org.ops4j.pax.logging:pax-logging-log4j2
      - org.ops4j.pax.logging:pax-logging-log4j2-maven-plugin
      - org.ops4j.pax.logging:pax-logging-logback
      - org.ops4j.pax.swissbox:pax-swissbox-property
      - org.ops4j.pax.url:pax-url-aether
      - org.ops4j.pax.url:pax-url-aether-support
      - org.ops4j.pax.web:pax-web-api
      - org.ops4j.pax.web:pax-web-extender-whiteboard
      - org.ops4j.pax.web:pax-web-jetty
      - org.ops4j.pax.web:pax-web-jsp
      - org.ops4j.pax.web:pax-web-runtime
      - org.ops4j.pax.web:pax-web-spi
      - org.ops4j.pax.web:pax-web-tomcat-common
      - org.osgi:org.osgi.namespace.extender
      - org.osgi:org.osgi.namespace.implementation
      - org.osgi:org.osgi.namespace.service
      - org.osgi:org.osgi.service.cm
      - org.osgi:org.osgi.service.component
      - org.osgi:org.osgi.service.component.annotations
      - org.osgi:org.osgi.service.event
      - org.osgi:org.osgi.service.jaxrs
      - org.osgi:org.osgi.service.jdbc
      - org.osgi:org.osgi.service.log
      - org.osgi:org.osgi.service.log.stream
      - org.osgi:org.osgi.service.metatype
      - org.osgi:org.osgi.service.prefs
      - org.osgi:org.osgi.util.converter
      - org.osgi:org.osgi.util.function
      - org.osgi:org.osgi.util.promise
      - org.osgi:org.osgi.util.pushstream
      - org.osgi:osgi.annotation
      - org.osgi:osgi.cmpn
      - org.osgi:osgi.core
      - org.ow2.asm:asm
      - org.ow2.asm:asm-analysis
      - org.ow2.asm:asm-commons
      - org.ow2.asm:asm-tree
      - org.ow2.asm:asm-util
      - org.reactivestreams:reactive-streams
      - org.slf4j:jcl-over-slf4j
      - org.slf4j:jul-to-slf4j
      - org.slf4j:slf4j-api
      - org.slf4j:slf4j-simple
      - org.threeten:threeten-extra
      - org.vesalainen.comm:javaxcomm
      - org.vesalainen:comm
      - org.vesalainen:dev
      - org.vesalainen:util
      - org.yaml:snakeyaml
      - si.uom:si-quantity
      - si.uom:si-units
      - tech.units:indriya
      - tech.uom.lib:uom-lib-common
