name: Trigger ci_build on Label

on:
  pull_request:
    types: [labeled]

jobs:
  trigger-build:
    if: ${{ github.event.label.name == 'rebuild' }}
    uses: actions/github-script@v7
    with:
      script: |
        const response = await github.rest.actions.createWorkflowDispatch({
          owner: context.repo.owner,
          repo: context.repo.repo,
          workflow_id: "ci-build.yml", // Name of the workflow file
          ref: context.ref, // Branch or tag to run the workflow on
          inputs: {
          }
        });
        console.log(response);
