name: Trigger ci_build on Label

on:
  pull_request:
    types: [labeled]

jobs:
  trigger-build:
    if: ${{ github.event.label.name == 'rebuild' }}
    uses: ./ci_build.yml@main
    with:
      job: build
