name: Trigger ci_build on Label

on:
  pull_request:
    types: [labeled]

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        #with:
        #  fetch-depth: 0
        #  sparse-checkout: |
        #    .github
      - name: List files
        run: |
          pwd
          find .
          echo "---------------"
          find .|grep ci-build.yml
      - name: Trigger CI Build
        if: ${{ github.event.label.name == 'rebuild' }}
        uses: ./.github/workflows/ci-build.yml
        with:
          job: build
