name: Trigger ci_build on Label

on:
  pull_request:
    types: [labeled]

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI Build
        if: ${{ github.event.label.name == 'rebuild' }}
        uses: .github/workflows/ci_build.yml
        with:
          job: build
