name: Rebuild PR

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      pr:
        description: 'PR number to rebuild'
        required: false
        default: '0'
      label:
        description: 'Label to trigger rebuild'
        required: false
        default: 'rebuild'

# grant permission
# - actions:write to allow rerun
# - PR:write to allow removing the label
# - checks:write to allow setting build status
permissions:
  actions: write
  checks: write
  pull-requests: write
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number || inputs.pr }}
  LABEL: ${{ github.event.label.name || inputs.label }}

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
    - name: Info
      env:
        GITHUB_EVENT: ${{ toJson(github.event) }}
      run: |
        echo "$GITHUB_EVENT"
        
    - name: Checkout
      if: github.head_ref == ''
      uses: actions/checkout@v4

    - name: Checkout merge
      if: github.head_ref != ''
      uses: actions/checkout@v4
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge

    - name: List Jobs
      run: |
        echo "Label: ${{ env.LABEL }}"
        echo "PR: ${{ env.PR_NUMBER }}"
        NUMBER=$(gh pr checks ${{ env.PR_NUMBER }} -R holgerfriedrich/openhab-core|grep -v "^rebuild"| sed -E 's#.*/([0-9]+)/job/([0-9]+)#\1#'|grep -ve '[[:alpha:]]'|sort -nu|head -n3|xargs|tr '\n' ' ')
        echo "Number of last 3 check jobs: $NUMBER"
        echo "NUMBER=$NUMBER">>$GITHUB_ENV

    - name: Trigger Rebuild
      if: ${{ env.LABEL == 'rebuild' }}
      env:
        PR: ${{ env.PR_NUMBER }}
        NUMBER: ${{ env.NUMBER }}
      run: |
        if [ -z "$NUMBER" ]; then
          echo "Error: Previous check run not found, cannot rebuild"
          exit 1
        fi
        for i in $(echo $NUMBER|tr ' ' '\n'); do
          echo   "Rebuilding PR #$i"
          gh run rerun $i
        done

    - name: Remove Label
      if: ${{ always() && env.LABEL == 'rebuild' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ env.PR_NUMBER }}
      run: |
        gh pr edit $PR --remove-label rebuild
